version: '3'
services:
  minio:
    image: minio/minio
    ports: 
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=dev
      - MINIO_SECRET_KEY=password
    command: server /data
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
