spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

minio:
  host: http://localhost:9000
  accesskey: dev
  secretkey: password
